### ISSUE TITLE
pip install fails due to permission error

### ISSUE THREAD

**Issue by wyup** [source-foundry/font-line#16]
Hello,
I'm a Fedora 27 user with Python 2.7.14 version.
When I type `pip install font-line` from ./local/share/fonts it gives the following error:

```
$ pip install font-line
Collecting font-line
  Using cached font_line-0.7.1-py2.py3-none-any.whl
Collecting standardstreams (from font-line)
  Using cached standardstreams-0.2.0-py2.py3-none-any.whl
Collecting commandlines (from font-line)
  Using cached commandlines-0.4.1-py2.py3-none-any.whl
Collecting fontTools (from font-line)
  Using cached fonttools-3.21.2-py2.py3-none-any.whl
Installing collected packages: standardstreams, commandlines, fontTools, font-line
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 365, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 854, in install
    strip_file_prefix=strip_file_prefix
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 1069, in move_wheel_files
    strip_file_prefix=strip_file_prefix,
  File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permiso denegado: '/usr/lib/python2.7/site-packages/standardstreams-0.2.0.dist-info'
```
It seems it can't write to /usr/lib/

**Comment by chrissimpkins** [comment]
Maybe try this:

https://stackoverflow.com/a/42021993

Let me know if that works.

**Comment by chrissimpkins** [comment]
Please feel free to reopen if this does not solve your problem
